FROM nvcr.io/nvidia/l4t-base:r32.2

RUN apt-get update && \
    apt-get install -y build-essential python3-dev python3-pip git cmake && \
    mkdir /scripts && \
    mkdir /dist && \
    mkdir /sources
